#!/bin/sh

init_python() {
  cat >solve.py <<EOL
#!/usr/bin/env python
import fileinput
import numpy as np

a = np.loadtxt(fileinput.input(), np.int32).T
EOL
  chmod +x solve.py
}

init_ruby() {
  for f in part1.rb part2.rb; do
    if ! [ -f $f ]; then
      echo '#!/usr/bin/env ruby' > "$f"
      chmod +x "$f"
    fi
  done
}

init_julia() {
  for f in part1.jl part2.jl; do
    if ! [ -f $f ]; then
      echo '#!/usr/bin/env julia' > "$f"
      chmod +x "$f"
    fi
  done
}

day="$(date '+%d')"
mkdir -p "$day"
cd "$day"
touch example

lng="${1:-python}"
case "$lng" in
  python|ruby|julia)
    init_${lng}
    ;;
  *)
    echo >&2 "Unknown language [${lng}]"
    exit 64
esac

aoc d -I
